<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content">

<h1>Puppet Facts</h1>

<?php
use Icinga\Application\Config;

$config = Config::module('puppetreports');
$rptdir = $config->get('facts', 'dir');

	// Requirements
	global $config;

	$config = array(
		'facts_dir' => $rptdir,
	);


	require_once('lib/spyc/spyc.php');
	$errors = array();

	if(!is_dir($config['facts_dir'])) {
		$errors[] = "The specified directory is not available.";
	}




if (isset($_GET) && array_key_exists('server', $_GET) && !empty($_GET['server'])) {
$array = Spyc::YAMLLoad($rptdir. '/'. htmlentities(mb_strtolower($_GET['server'])) .'.yaml');

$arrvalues = $array['--- !ruby/object']['values'];



echo  "<h2>Host: ".$_GET['server']."</h2>";
echo "<table class='common-table'>";
echo "<thead><tr><th>Key</th><th>Value</th></tr></thead>";
foreach ( $arrvalues as $key => $value ) {
	  echo "<tr>";
    	echo "<td>".$key."</td><td>".$value."</td>";
	  echo "</tr>";

}
echo "</table>";



} else {

	$servers = array();
	if($handle = opendir($rptdir)) {
		while (false !== ($entry = readdir($handle))) {
			if($entry == "." || $entry == "..")
				continue;

			if(!is_dir($rptdir . "/" . $entry)) {
				$servers[] = str_replace('.yaml', '', $entry);
			}
		}
		closedir($handle);
	}
	asort($servers);


echo '<table data-base-target="_next" class="common-table"><tbody>';
foreach($servers as $server) {
	echo '<tr>';

	echo '<td><a href="/icingaweb2/puppetreports/index/facts?server=' . urlencode($server) . '">';
	echo htmlentities($server) . '</a></td>';
	
	echo '<tr>';

}
echo '</tbody></table>';


}

?>

			


</div>
