<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content">

<h1>Puppet Facts</h1>

<?php
use Icinga\Application\Config;

$config = Config::module('puppetreports');
$rptdir = $config->get('facts', 'dir');

	// Requirements
	global $config;

	$config = array(
		'facts_dir' => $rptdir,
	);


	require_once('lib/spyc/spyc.php');
	$errors = array();

	// Sanity checks
	if(!is_dir($config['facts_dir'])) {
		$errors[] = "The specified facts dir couldn't be accessed.";
	}


//$rptdir = '/var/lib/puppet/yaml/facts';


if (isset($_GET) && array_key_exists('server', $_GET) && !empty($_GET['server'])) {
$array = Spyc::YAMLLoad($rptdir. '/'. htmlentities(mb_strtolower($_GET['server'])) .'.yaml');

$arrvalues = $array['--- !ruby/object']['values'];

/*
echo "<table class='common-table'>";
                    echo "<tr><td>fqdn</td><td>".$arrvalues['fqdn']."</td></tr>";
                    echo "<tr><td>hostname</td><td>".$arrvalues['hostname']."</td></tr>";
                    echo "<tr><td>domain</td><td>".$arrvalues['domain']."</td></tr>";

                    echo "<tr><td>virtual</td><td>".$arrvalues['virtual']."</td></tr>";
                    echo "<tr><td>is_virtual</td><td>".$arrvalues['is_virtual']."</td></tr>";
                    echo "<tr><td>hardwaremodel</td><td>".$arrvalues['hardwaremodel']."</td></tr>";
                    echo "<tr><td>architecture</td><td>".$arrvalues['architecture']."</td></tr>";

                    echo "<tr><td>ipaddress</td><td>".$arrvalues['ipaddress']."</td></tr>";
                    echo "<tr><td>macaddress</td><td>".$arrvalues['macaddress']."</td></tr>";
                    echo "<tr><td>netmask</td><td>".$arrvalues['netmask']."</td></tr>";

                    echo "<tr><td>manufacturer</td><td>".$arrvalues['manufacturer']."</td></tr>";
                    echo "<tr><td>serialnumber</td><td>".$arrvalues['serialnumber']."</td></tr>";
                    echo "<tr><td>productname</td><td>".$arrvalues['productname']."</td></tr>";

                    echo "<tr><td>memorysize</td><td>".$arrvalues['memorysize']."</td></tr>";
                    echo "<tr><td>memoryfree</td><td>".$arrvalues['memoryfree']."</td></tr>";

                    echo "<tr><td>kernel</td><td>".$arrvalues['kernel']."</td></tr>";
                    echo "<tr><td>kernelmajversion</td><td>".$arrvalues['kernelmajversion']."</td></tr>";
                    echo "<tr><td>kernelrelease</td><td>".$arrvalues['kernelrelease']."</td></tr>";
                    echo "<tr><td>kernelversion</td><td>".$arrvalues['kernelversion']."</td></tr>";

                    echo "<tr><td>operatingsystem</td><td>".$arrvalues['operatingsystem']."</td></tr>";
                    echo "<tr><td>operatingsystemmajrelease</td><td>".$arrvalues['operatingsystemmajrelease']."</td></tr>";
                    echo "<tr><td>operatingsystemrelease</td><td>".$arrvalues['operatingsystemrelease']."</td></tr>";
                    echo "<tr><td>osfamily</td><td>".$arrvalues['osfamily']."</td></tr>";

                    echo "<tr><td>physicalprocessorcount</td><td>".$arrvalues['physicalprocessorcount']."</td></tr>";
                    echo "<tr><td>processor0</td><td>".$arrvalues['processor0']."</td></tr>";
                    echo "<tr><td>processorcount</td><td>".$arrvalues['processorcount']."</td></tr>";

                    echo "<tr><td>timezone</td><td>".$arrvalues['timezone']."</td></tr>";
                    echo "<tr><td>uptime</td><td>".$arrvalues['uptime']."</td></tr>";
                    echo "<tr><td>uptime_days</td><td>".$arrvalues['uptime_days']."</td></tr>";
                    echo "<tr><td>uptime_hours</td><td>".$arrvalues['uptime_hours']."</td></tr>";
                    echo "<tr><td>uptime_seconds</td><td>".$arrvalues['uptime_seconds']."</td></tr>";

                    echo "<tr><td>_timestamp</td><td>".$arrvalues['_timestamp']."</td></tr>";
echo "</table>";          
*/



echo "<table class='common-table'>";
echo "<thead><tr><th>Key</th><th>Value</th></tr></thead>";
foreach ( $arrvalues as $key => $value ) {
	  echo "<tr>";
    	echo "<td>".$key."</td><td>".$value."</td>";
	  echo "</tr>";

}
echo "</table>";

/*
echo '<pre>';
print_r($array);
echo '</pre>';

echo '<pre>';
echo Spyc::YAMLDump($array);
echo '</pre>';
*/


} else {

	$servers = array();
	if($handle = opendir($rptdir)) {
		while (false !== ($entry = readdir($handle))) {
			if($entry == "." || $entry == "..")
				continue;

			if(!is_dir($rptdir . "/" . $entry)) {
				$servers[] = str_replace('.yaml', '', $entry);
			}
		}
		closedir($handle);
	}
	asort($servers);


echo '<table data-base-target="_next" class="common-table"><tbody>';
foreach($servers as $server) {
	echo '<tr>';

	//echo '<td></td>';
	echo '<td><a href="facts?server=' . urlencode($server) . '">';
	echo htmlentities($server) . '</a></td>';
	
	echo '<tr>';

}
echo '</tbody></table>';


}

?>

			


</div>
